Makefile, cmd/bench/main.go, cmd/internal/worker.go
- Add double comment for `start` sections
- Remove unused error from logging
- Refactoring workers
- `parsed` channel responsible for stopping of Parser-worker
- `sentOut` channel responsible for stopping of Sender-worker
- `Wait` method waits for
- wait until all request workers stopped
- wait until sender worker stopped
- wait until parser worker is stopped
=> Fixed bug with premature termination

cmd/internal/gen.go
emit.AppCallWithOperationAndArgs creates an array of arguments for invocation
with Array function that doesn't really support ints, though works fine with
int64.
=> gen: fix tx generation, int fails to be emitted

.docker/build/Dockerfile.sharp, .docker/build/sharp.rpc.config.json
1. There's no ImportBlocks plugin in v3.0.0-preview2. The latest version
of this plugin is in v3.0.0-preview1 release.
2. Links of the other preview2 plugins have been changed a bit.
=> build: fix modules links in Dockerfile.sharp

cmd/internal/client.go
RPC API has been changed, `sendrawtransaction` returns tx hash now.
=> cmd: change SendTx expected result

cmd/dump/chain.go
C# node will refuse to work with blocks containing 4 signatures and neo-go
will also do that with recent changes.
=> dump: only add 3 signatures out of 4 for 4-node setups

cmd/internal/report.go, cmd/internal/worker.go
1. Refactor some old 2-x code.
2. Do not pay attention to zero TPS values at the start and at the end of the test.
=> cmd: be carefull with counting zero TPS values

.docker/build/Dockerfile.sharp, .docker/build/sharp.rpc.config.json, .docker/ir/go.protocol.privnet.four.yml, .docker/ir/go.protocol.privnet.one.yml, .docker/ir/go.protocol.privnet.single.yml, .docker/ir/go.protocol.privnet.three.yml, .docker/ir/go.protocol.privnet.two.yml, .docker/rpc/go.protocol.yml, .docker/rpc/rpc.protocol.single.yml, Makefile, cmd/bench/main.go, cmd/internal/client.go, cmd/internal/report.go, cmd/internal/worker.go
A set of small but important fixes.
=> *: C# RocksDBStore, bench concurrent HTTP connections, Go monitoring and others 

.docker/build/Dockerfile.sharp, .docker/build/Dockerfile.sharp.sources, Makefile, README.md
Add ability to build the following services from sources:
- neo
- neo-vm
- neo-cli
- neo plugins
Important: it's up to you to keep an eye on services versions matching.
This dockerfile just replaces specified .dlls with the built one, so be
careful while setting CLIBRANCH, MODULESBRANCH, NEOVMBRANCH and NEOBRANCH
env variables.
=> build: add Dockerfile to build C# node from sources

.docker/build/Dockerfile.bench, .docker/build/Dockerfile.golang
It's important to set the version of Builder layer explicitly. At
the current moment Go 1.15 gives us 22% decline on single-node consensus
test comparing with Go 1.14, so let it be 1.14 for now.
=> build: specify golang version of base layer explicitly

cmd/bench/main.go, cmd/internal/report.go, cmd/internal/worker.go, plot.py
1. Save to log the time-from-start for CPU and Memory
2. Save to log the time-between-blocks and txs count for TPS
=> *: logging improvements

.docker/ir/go.protocol.template.yml
We should be able to use bench environment for manual tests, so let's
not limit MaxGasInvoke, otherwise it's impossible to use
`invokefunction` RPC call.
=> config: explicitly set MaxGasInvoe RPC configuration to -1

.docker/ir/docker-compose.go.yml, .docker/ir/docker-compose.sharp.yml, .docker/ir/docker-compose.single.go.yml, .docker/ir/docker-compose.single.sharp.yml, .docker/rpc/docker-compose.go.yml, .docker/rpc/docker-compose.sharp.yml
Go nodes can stall on logging:
1 @ 0x482245 0x4800ea 0x49afa9 0x49af34 0x4a1b87 0x4a1b57 0x959f5c 0x94d046 0x94e997 0x968b7f 0xaee3de 0xaf10ad 0x9495b5 0xaeea15 0xae38b7 0x781894 0x784c23 0x78068c 0x467781
0x482244	syscall.Syscall+0x4									syscall/asm_linux_amd64.s:18
0x4800e9	syscall.write+0x59									syscall/zsyscall_linux_amd64.go:914
0x49afa8	syscall.Write+0x178									syscall/syscall_unix.go:214
0x49af33	internal/poll.(*FD).Write+0x103								internal/poll/fd_unix.go:268
0x4a1b86	os.(*File).write+0x76									os/file_unix.go:280
0x4a1b56	os.(*File).Write+0x46									os/file.go:153
0x959f5b	go.uber.org/zap/zapcore.(*lockedWriteSyncer).Write+0x6b					go.uber.org/zap@v1.10.0/zapcore/write_syncer.go:66
0x94d045	go.uber.org/zap/zapcore.(*ioCore).Write+0x105 …
=> compose: disable logging for all nodes

.docker/build/Dockerfile.golang, .docker/build/Dockerfile.sharp.sources.from_binaries, .docker/build/Dockerfile.sharp.sources.from_local_dependencies, Makefile, cmd/dump/main.go, cmd/go.mod, cmd/go.sum, cmd/internal/gen.go
Related #49 .
Need to wait until preview4 to update C# nodes.
=> Update neo-go version

cmd/internal/report.go, cmd/internal/worker.go
Close #53.
We need to count average TPS value as accepted txs count devided by
overall accepted blocks time.
NOTE: In case of early interrupt TPS value can still be more than RPS
value, because we take into account only those transactions which are
already in chain and do not pay attention to the mempooled ones.
=> *: fix average TPS reporter

.docker/build/Dockerfile.golang, cmd/go.mod, cmd/go.sum, cmd/internal/gen.go
Related https://github.com/nspcc-dev/neo-go/issues/1627
Results for master (HEAD^):
```
TXs ≈ 280374
RPS ≈ 934.577
RPC Errors  ≈ 705503 / 71.561%
TPS ≈ 949.643
DefaultMSPerBlock = 5000
CPU ≈ 86.527%
Mem ≈ 3139.020MB
```
Results with cache for management contract:
```
TXs ≈ 374087
RPS ≈ 1337.604
RPC Errors  ≈ 625912 / 62.591%
TPS ≈ 1403.943
DefaultMSPerBlock = 5000
CPU ≈ 86.978%
Mem ≈ 3316.376MB
```
=> cmd/gen: fix NEO contract hash

.docker/build/Dockerfile.sharp, .docker/build/Dockerfile.sharp.sources.from_binaries, .docker/build/Dockerfile.sharp.sources.from_local_dependencies
Close #56.
I have tested (2Go+2C#) and (1Go+3C#) setups with GoRPC node and default Transfers transactions, works fine.
Updated both released and sources cases. Needs to be merge after #54 (there's a useful NEO hash adjustment).
Related: https://github.com/nspcc-dev/neo-go/pull/1633
=> *: update C# to preview4

.docker/ir/go.protocol.template.yml
These are expected to be tuned for particular networks and default values are
set based on 15s block time expectations. These settings are completely
irrelevant for single node, but our default four node setup uses 5s block
time, so I think we can adjust ping time to 10s with timeout of 30s for this
network.
It technically tunes Go node without tuning C# node in the same way, but
unfortunately C# just doesn't have appropriate settings.
=> go.template: use shorter ping interval and timeout

.docker/build/Dockerfile.sharp
I should've checked this, but image built from sources of course works
fine. It doesn't work from released binaries though as there is no 3.0.2
release of neo-modules. So fix it.
=> build: use 3.0.1 modules for 3.0.2 C# node

.docker/ir/docker-compose.go.yml, .docker/ir/docker-compose.mixed.yml, .docker/ir/docker-compose.sharp.yml
This allows us to easily test scenarios where transactions are pushed directly on consensus nodes. Refs https://github.com/nspcc-dev/neo-go/issues/591 .
This is another case worth considering and without rate limiting it leads to something like this on my machine:
```
>./runner.sh -w 100 -m wrk -l -z 10m -a neo_go_node_one:30333 -a neo_go_node_two:30334 -a neo_go_node_three:30335 -a neo_go_node_four:30336 -i /dump.txs
...
2021/08/28 13:34:16 empty block: 7
2021/08/28 13:34:19 CPU: 38.928%, Mem: 169.590MB
2021/08/28 13:34:29 CPU: 96.278%, Mem: 394.059MB
2021/08/28 13:34:31 #8: 8267 transactions in 5056 ms - 1635.087025 tps
2021/08/28 13:34:38 CPU: 80.635%, Mem: 639.059MB
2021/08/28 13:34:46 CPU: 46.457%, Mem: 733.578MB
2021/08/28 13:34:54 CPU: 20.099%, Mem: 667.672MB
2021/08/28 13:35:02 …
```
=> Expose RPC ports for consensus nodes

.docker/build/Dockerfile.golang, .docker/build/Dockerfile.sharp, .docker/build/Dockerfile.sharp.sources.from_binaries, .docker/build/Dockerfile.sharp.sources.from_local_dependencies, .docker/build/go.entrypoint.sh, .docker/build/sharp.entrypoint.sh, .docker/ir/docker-compose.go.yml, .docker/ir/docker-compose.mixed.yml, .docker/ir/docker-compose.sharp.yml, .docker/rpc/docker-compose.go.yml, README.md, runner.sh
Delaying is done inside the container via `tc` command.
It can be enabled via environment $DELAY variable:
`DELAY=1000ms make start.GoFourNodes10wrk`
For this to work container needs CAP_NET_ADMIN capability.
Signed-off-by: Evgenii Stratonikov <evgeniy@nspcc.ru>
=> .docker: add network delay

Makefile
Testing single node takes less than 20 seconds now, 1M is just not enough.
=> Makefile: make 3M tx a new standard

.docker/build/Dockerfile.sharp, .docker/build/Dockerfile.sharp.sources.from_binaries, .docker/build/Dockerfile.sharp.sources.from_local_dependencies
Use tags which required some changes to "from_local_dependencies" version
since it unpacks "v3.3.1.zip" into "neo-3.3.1" (missing 'v').
=> docker: update C# node to 3.3.1

.docker/build/Dockerfile.golang, cmd/go.mod, cmd/go.sum
Depends on #142, I'd like to see how the newly-added GA work.
=> *: update NeoGo image and deps

.github/workflows/tests.yml
Warning: CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
=> workflows: update CodeQL version

cmd/internal/prepare.go
Fix the following error on short-blocks setup:
```
2024-04-23 12:54:47 2024/04/23 10:54:47 Used [go-node:20331] rpc addresses
2024-04-23 12:54:47 2024/04/23 10:54:47 Run benchmark for Go4x1_Block_100 :: NEO-GO
2024-04-23 12:54:57 2024/04/23 10:54:57 Read 3000000 txs from /dump.txs
2024-04-23 12:55:06 2024/04/23 10:55:06 CPU: 4.959%, Mem: 243.746MB
2024-04-23 12:55:13 2024/04/23 10:55:13 Done 16.094694633s
2024-04-23 12:55:13 2024/04/23 10:55:13 Init 10 workers / 5m0s time limit (3000000 txs will try to send)
2024-04-23 12:55:13 2024/04/23 10:55:13 Prepare chain for benchmark
2024-04-23 12:55:13 2024/04/23 10:55:13 Determined validators count: 4
2024-04-23 12:55:13 2024/04/23 10:55:13 Sending NEO and GAS transfer tx
2024-04-23 12:55:13 2024/04/23 10:55:13 could not create blocks: timeout …
```
=> internal: adjust awaiting timeout for setup transactions

.docker/build/Dockerfile.sharp.sources.from_binaries, .docker/build/Dockerfile.sharp.sources.from_local_dependencies, README.md, runner.sh
=> .docker: ajust Dockerfiles for ARM-based Mac architecture

Makefile, README.md, cmd/config/main.go, runner.sh
`./runner.sh --nodes mixed --rpc sharp -d "Mytest" -m rate -q 50 -z 5m -t 30s --time $(TIME_PER_BLOCK)`
example:
```
TARGETS := start.GoFourNodes10wrk start.GoFourNodes30wrk start.GoFourNodes100wrk
TIME_BLOCKS := 5000 1000 500 200 100
run-block-tests:
@$(foreach target,$(TARGETS), \
$(foreach time,$(TIME_BLOCKS), \
echo "Running $(target) with time per block $(time) ms" && \
$(MAKE) $(target) TIME_PER_BLOCK=$(time); \
) \
)
```
=> config: add `--msPerBlock` flag

.docker/build/Dockerfile.golang, cmd/internal/client.go
Otherwise we have a tremendous number of RPC errors in our logs and small number of blocks since no retries happen:
```
Go7x1 :: NEO-GO_0.105.1 / 100 wrk / 5m0s
TXs ≈ 650000
RPS ≈ 9236.825
RPC Errors  ≈ 2350000 / 78.333%
TPS ≈ 9295.009
DefaultMSPerBlock = 5000
CPU ≈ NaN%
Mem ≈ NaNMB
MillisecondsFromStart, CPU, Mem
DeltaTime, TransactionsCount, TPS
5102, 50000, 9800.078
5454, 50000, 9167.583
5435, 50000, 9199.632
5368, 50000, 9314.456
5367, 50000, 9316.192
5384, 50000, 9286.776
5408, 50000, 9245.562
5418, 50000, 9228.498
5408, 50000, 9245.562
5451, 50000, 9172.629
5376, 50000, 9300.595
5378, 50000, 9297.136
5381, 50000, 9291.953
```
=> cmd: fix mempool OOM error detection for NeoGo node

cmd/bench/main.go, cmd/internal/worker.go
Once mempool OOm error happens, worker should wait for a while until block processing finishes. Make this awaiting interval depend on MSPerBlock protocol setting so that it's possible to perform precise calculations for low MSPerBlock setting.
=> cmd: make mempool OOM error handler more adaptive

README.md, cmd/bench/main.go, cmd/internal/worker.go, runner.sh
=> bench: add workers into rate mode

.github/workflows/build.yml, .github/workflows/tests.yml, .gitignore, Makefile, README.md, cmd/bench/main.go, cmd/internal/settings.go, runner.sh
`./runner.sh -e -d "Go4x1" -m rate -q 1000 -z 5m -t 30s -a 192.168.1.100:20331 -a 192.168.1.101:20331`
Close #160
=> *: add external flag for testing external networks

.docker/build/Dockerfile.bench, .docker/build/Dockerfile.golang, .docker/build/Dockerfile.sharp
Fix the following Docker image build warning that stops the build:
```
1 warning found (use docker --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 3)
```
=> build: migrate to AS keyword usage in Dockerfiles

.docker/build/Dockerfile.golang
Should be a part of 7538ebb4e9ae24c9ef065cf0817b3c5507a89a8b, otherwise old NeoGo version fails to read config generated by new NeoGo version:
```
failed to unmarshal config YAML: yaml: unmarshal errors:
line 18: field NeoFSStateSyncExtensions not found in type config.ProtocolConfiguration
line 40: field RemoveUntraceableHeaders not found in type config.ApplicationConfiguration
line 43: field SaveInvocations not found in type config.ApplicationConfiguration
line 129: field NeoFSBlockFetcher not found in type config.ApplicationConfiguration
```
=> .docker: bump NeoGo image version to 0.108.0
