.docker/build/Dockerfile.sharp
.docker/build/go.entrypoint.sh
.docker/build/sharp.entrypoint.sh
.docker/ir/docker-compose.sharp.yml
.docker/rpc/docker-compose.sharp.yml
.docker/rpc/sharp.config.json
.docker/rpc/sharp.wallet.json

Closes #3.
Now we're able to test both C# and Go implementations with both single and 4x1 configurations.

*: sharp node fixes

---

.docker/rpc/docker-compose.single.rpc.yml
.docker/rpc/rpc.protocol.single.yml
Makefile

Following configs were added to Makefile:
Sharp 4x + GoRPC (workers + rate)
SharpSingle + GoRPC (workers + rate)

bench: add tests for Sharp+GoRPC consensus

---

cmd/internal/report.go

Each Sender iteration we count average RPS for the current moment
(AvgRPS=SentTransactionsCount/TimeSinceTestStart) so we need to store
only the last AvgRPS value, not all of them.

cmd: fix the way we count RPS

---

Makefile
cmd/config/main.go

cmd: add ability to configure node database via flag

---

Makefile

They were just broken, referencing output file.

Makefile: fix dumps dependencies

---

.docker/rpc/docker-compose.go.yml
.docker/rpc/docker-compose.sharp.yml
.docker/rpc/docker-compose.single.yml
Makefile

Makefile: move dump.txs to build directory

---

.docker/build/Dockerfile.golang
.docker/ir/go.protocol.template.yml
.docker/ir/sharp.protocol.template.yml
cmd/bench/main.go
cmd/go.mod
cmd/go.sum
cmd/internal/client.go
cmd/internal/gen.go
cmd/internal/reader.go
cmd/internal/worker.go

cmd: introduce transactions queue

---

.docker/build/Dockerfile.golang
.docker/build/Dockerfile.sharp.sources.from_local_dependencies
.docker/build/sharp.dbft.config.json
.docker/build/sharp.entrypoint.sh
.docker/ir/docker-compose.sharp.yml
.docker/ir/docker-compose.single.sharp.yml
.docker/ir/sharp.protocol.template.yml
.docker/rpc/docker-compose.sharp.yml
Makefile
cmd/dump/main.go
cmd/go.mod
cmd/go.sum
cmd/internal/gen.go

Make it compatible with current masters for both nodes.

Post-preview4 update

---

.docker/build/Dockerfile.golang
.docker/build/Dockerfile.sharp
.docker/build/Dockerfile.sharp.sources.from_local_dependencies
.docker/ir/docker-compose.mixed.yml
Makefile
cmd/dump/main.go
cmd/go.mod
cmd/go.sum
cmd/internal/gen.go

dump:
* update policy contract hash
* policy setters no longer return result
Don't build RocksDB when using binaries, it's no longer needed.

update go to pre-preview5 and C# node to preview5 official

---

.docker/build/Dockerfile.golang
.docker/build/Dockerfile.sharp
.docker/build/Dockerfile.sharp.sources.from_binaries
.docker/build/Dockerfile.sharp.sources.from_local_dependencies
.docker/build/sharp.statesdumper.config.json
cmd/go.mod
cmd/go.sum

C# container built with `Dockerfile.sharp.sources.from_binaries` is unhealthy after start, but consensus is running and blocks are being accepted. Still investigating the issue.

build: final preview5 updates

---

cmd/bench/main.go

Signed-off-by: Evgenii Stratonikov <evgeniy@nspcc.ru>

bench: omit prepare tx from TPS report, fix #96

---

plot.py

Maybe it's 4K monitor, maybe it's trying to plot many lines at once, but I
feel current image size to be somewhat small.

plot: make figure a bit larger

---

cmd/internal/worker.go

Signed-off-by: Evgenii Stratonikov <evgeniy@nspcc.ru>

bench: retry fetching block on error, fix #98

---

.docker/ir/docker-compose.go.7.yml
.docker/ir/docker-compose.mixed.7.yml
.docker/ir/docker-compose.sharp.7.yml
.docker/ir/go.protocol.template.yml
.docker/ir/sharp.protocol.template.yml
.docker/ir/template.data.yml
.docker/ir/wallet.five.json
.docker/ir/wallet.four.json
.docker/ir/wallet.one.json
.docker/ir/wallet.seven.json
.docker/ir/wallet.six.json
.docker/ir/wallet.three.json
.docker/rpc/docker-compose.go.7.yml
.docker/rpc/docker-compose.sharp.7.yml
.docker/rpc/docker-compose.sharp.yml
.env
.gitignore
Makefile
cmd/config/main.go
cmd/internal/prepare.go
runner.sh

Add 7+2 workload

---

runner.sh

Minor documentation update after https://github.com/nspcc-dev/neo-bench/pull/102.

runner.sh: help text update

---

Makefile
README.md

And adjust `make test` target.

README: update usage example

---

.github/workflows/dco.yml

workflows: enable DCO

---

.github/workflows/build.yml
.github/workflows/tests.yml
.golangci.yml
CODEOWNERS
cmd/config/main.go
cmd/gen/main.go
cmd/internal/client.go
cmd/internal/docker.go
cmd/internal/grace.go
cmd/internal/prepare.go
cmd/internal/prepare_util.go
cmd/internal/reader.go
cmd/internal/report.go
cmd/internal/worker.go

- Ensure that every PR doesn't break at least the building make target. Manual dispatch is also supported.
- Add linter, CodeQL and testing jobs.
- Add codeowners.
- Fix linting issues.
Close #141.

.github: add building and testing workflows

---

.docker/ir/docker-compose.go.7.yml
.docker/ir/docker-compose.go.yml
.docker/ir/docker-compose.mixed.7.yml
.docker/ir/docker-compose.mixed.yml
.docker/ir/docker-compose.node.yml
.docker/ir/docker-compose.sharp.7.yml
.docker/ir/docker-compose.sharp.yml
.docker/ir/docker-compose.single.go.yml
.docker/ir/docker-compose.single.sharp.yml
.docker/rpc/docker-compose.bench.yml
.docker/rpc/docker-compose.go.7.yml
.docker/rpc/docker-compose.go.yml
.docker/rpc/docker-compose.sharp.7.yml
.docker/rpc/docker-compose.sharp.yml
.docker/rpc/docker-compose.single.yml
.github/workflows/build.yml
.github/workflows/tests.yml
Makefile
README.md
runner.sh

*: migrate to Docker Compose V2

---

.github/workflows/dco.yml
.github/workflows/tests.yml

workflows: take care of Linter job name

---

cmd/internal/docker.go

According to https://github.com/nspcc-dev/.github/pull/42.

Fix linter errors
